// import { extend } from 'lodash';
// import { getGetters } from './getters';
// import { actions } from './actions';
// import { mutations } from './mutations';
// import { heroModuleTypes } from './types';
// export const HERO_MODULE = 'hero';
// export const heroModuleInstance = getDataObjectsModule<ILead>(leadsManager);
// extend(heroModuleInstance.state, { tagsFilter: null as ILeadState, countLeadsWithNoTag: null as ILeadState });
// extend(heroModuleInstance.actions, actions);
// extend(heroModuleInstance.mutations, mutations);
// extend(heroModuleInstance.getters, getGetters());
